 
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE';
export const SUBMITTING_CREATE_NOTE = 'SUBMITTING_CREATE_NOTE';
export const RESET_CREATE_NOTE = 'RESET_CREATE_NOTE';
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const GET_ALL_NOTES = 'GET_ALL_NOTES';
export const GET_ALL_VERIFIED_NOTES = 'GET_ALL_VERIFIED_NOTES';
export const LOG_OUT = "LOG_OUT";

export const REGISTRATION_SUCCESS = "REGISTRATION_SUCCESS"
export const REGISTRATION_FAIL = "REGISTRATION_FAIL"

export const NOTIFICATION_SUCCESS = 'NOTIFICATION_SUCCESS';
export const NOTIFICATION_FAIL = 'NOTIFICATION_FAIL';

export const ADDSTORY_FAIL = 'ADDSTORY_FAIL'; 
export const ADDSTORY_SUCCESS = 'ADDSTORY_SUCCESS';

export const GET_FRIENDS_FAIL = 'GET_FRIENDS_FAIL'; 
export const GET_FRIENDS_SUCCESS = 'GET_FRIENDS_SUCCESS';

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAIL = 'GET_USER_FAIL';

export const GET_STORY_SUCCESS = 'GET_STORY_SUCCESS';
export const GET_STORY_FAIL = 'GET_STORY_FAIL'

export const VIBES_SUCCESS = 'VIBES_SUCCESS';
export const VIBES_FAIL = 'VIBES_FAIL';

export const VENUE_SUCCESS = 'VENUE_SUCCESS';
export const VENUE_FAIL = 'VENUE_FAIL';

export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';
export const LOCATION_FAIL = 'LOCATION_FAIL';

export const IMAGE_UPLOAD_DONE = 'IMAGE_UPLOAD_DONE';
export const IMAGE_DELETION_DONE = 'IMAGE_DELETION_DONE';

export const LIKECOUNT_SUCCESS = 'LIKECOUNT_SUCCESS'
export const LIKECOUNT_FAIL = 'LIKECOUNT_FAIL'

export const ALLOUNT_SUCCESS = 'ALLCOUNT_SUCCESS'
export const ALLCOUNT_FAIL = 'ALLCOUNT_FAIL'
 
export const GET_SYSTEM_GENDERS = "GET_SYSTEM_GENDERS"

export const VENUECOUNT_SUCCESS="VENUECOUNT_SUCCESS"
export const VENUECOUNT_FAIL = "VENUECOUNT_FAIL"

export const GET_PROCESSING_DONE = "GET_PROCESSING_DONE"
 
export const SEND_MESSAGE = "SEND_MESSAGE"

export const EDIT_USER_FAIL = "EDIT_USER_FAIL"
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS"

export const ADD_VENUE_SUCCESS = "ADD_VENUE_SUCCESS"
export const ADD_VENUE_FAIL = "ADD_VENUE_FAIL"

export const GET_ALL_FRIENDS_SUCCESS ="GET_ALL_FRIENDS_SUCCESS"
export const GET_ALL_FRIENDS_FAIL ="GET_ALL_FRIENDS_FAIL"